- hosts: all
  tasks:
          - name : Add yum repo
            yum_repository :
                    name : docker
                    description : My docker repo
                    baseurl : https://download.docker.com/linux/centos/7/x86_64/stable/
                    gpgcheck : no
            register : yum_status
          - debug :
                  var : yum_status



          - name : install docker
            package : 
                name : "docker-ce-18.09.1-3.el7.x86_64"
                state : present 
            register : install_status
          - debug :
                    var : install_status



          - name : start services 
            service :
                    name : "docker"
                    state : started
                    enabled : yes
            register : service_status
          - debug :
                  var : service_status



          - command : pip3 install docker
            register : pip_status
          - debug :
                  var : pip_status



          - name : create directory
            file:
                    path: /workspace
                    state : directory
            register : dir_status
          - debug :
                  var : dir_status



          - name : copy webpages
            copy : 
                src: index.html
                dest: /workspace
            register : copy_status
          - debug :
                  var : copy_status



          - name : Pull httpd 
            docker_container :
                    name : Webserver
                    image : httpd
                    state: started
                    exposed_ports :
                    - 80
                    ports: 
                    - 8081:80
                    volumes:
                    - /workspace:/usr/local/apache2/htdocs
            register : my_container_status
          - debug :
                  var : my_container_status

                    
